# Generated by Django 5.1.1 on 2024-10-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogUser',
        ),
    ]
